import {CommonModule} from '@angular/common';
import {Component,ElementRef,OnDestroy,ViewChild,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {FilesetResolver,ImageSegmenter} from '@mediapipe/tasks-vision';
type Stage='intro'|'camera'|'countdown'|'recording'|'result';
@Component({selector:'app-root',standalone:true,imports:[CommonModule,FormsModule],templateUrl:'./app.component.html',styleUrl:'./app.component.css'})
export class CardAppComponent implements OnDestroy{
 @ViewChild('camera') camera?:ElementRef<HTMLVideoElement>;@ViewChild('replay') replay?:ElementRef<HTMLVideoElement>;@ViewChild('cardCanvas') cardCanvas?:ElementRef<HTMLCanvasElement>;
 readonly stage=signal<Stage>('intro');readonly countdown=signal(10);readonly error=signal('');readonly isSharing=signal(false);readonly cardLoading=signal(false);
 playerName='';playerPosition='ST';playerNumber=10;replayUrl='';posterUrl='';private stream?:MediaStream;private recordedClip?:Blob;private segmenter?:ImageSegmenter;private frameId?:number;private busy=false;private template=new Image();private transparentTemplate?:HTMLCanvasElement;
 async openCamera(){this.error.set('');try{this.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1080},height:{ideal:1920}},audio:false});this.stage.set('camera');setTimeout(()=>{if(this.camera)this.camera.nativeElement.srcObject=this.stream!;});}catch{this.error.set('Camera access is needed. Allow it in your browser settings.');}}
 async startSequence(){this.stage.set('countdown');for(let n=10;n>0;n--){this.countdown.set(n);await this.delay(1000);}await this.record();}
 private async record(){if(!this.stream)return;this.stage.set('recording');const types=['video/webm;codecs=vp9','video/webm','video/mp4'];const type=types.find(t=>MediaRecorder.isTypeSupported(t))||'';const recorder=new MediaRecorder(this.stream,type?{mimeType:type}:undefined);const parts:BlobPart[]=[];recorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data)};const stopped=new Promise<void>(r=>recorder.onstop=()=>r());recorder.start(100);await this.delay(2000);recorder.stop();await stopped;this.recordedClip=new Blob(parts,{type:recorder.mimeType});this.replayUrl=URL.createObjectURL(this.recordedClip);this.stage.set('result');setTimeout(()=>void this.startRenderer(),100);}
 private async startRenderer(){const video=this.replay?.nativeElement;if(!video||!this.cardCanvas)return;this.cardLoading.set(true);try{await Promise.all([this.loadTemplate(),this.loadSegmenter()]);await new Promise<void>(r=>{if(video.readyState>=2)r();else video.onloadeddata=()=>r()});await video.play();this.render();}catch(e){console.warn('Background removal unavailable',e);await this.loadTemplate();this.fallback();}finally{this.cardLoading.set(false);}}
 private async loadSegmenter(){if(this.segmenter)return;const vision=await FilesetResolver.forVisionTasks('./mediapipe/wasm');this.segmenter=await ImageSegmenter.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_segmenter/float16/latest/selfie_segmenter.tflite',delegate:'GPU'},runningMode:'VIDEO',outputCategoryMask:false,outputConfidenceMasks:true});}
 private loadTemplate(){if(this.transparentTemplate)return Promise.resolve();return new Promise<void>((r,j)=>{this.template.onload=()=>{this.transparentTemplate=this.removeCheckerboard(this.template);r();};this.template.onerror=()=>j(new Error('Card artwork failed to load'));this.template.src='./cards/kora-blue-gold-template.png';});}
 private removeCheckerboard(image:HTMLImageElement){const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const ctx=canvas.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(image,0,0);const data=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<data.data.length;i+=4){const r=data.data[i],g=data.data[i+1],b=data.data[i+2],spread=Math.max(r,g,b)-Math.min(r,g,b),light=(r+g+b)/3;if(spread<14&&light>85&&light<235)data.data[i+3]=0;}ctx.putImageData(data,0,0);return canvas;}
 private render(){const video=this.replay?.nativeElement,canvas=this.cardCanvas?.nativeElement,ctx=canvas?.getContext('2d');if(!video||!canvas||!ctx||!this.segmenter)return;if(!this.busy&&video.readyState>=2){this.busy=true;this.segmenter.segmentForVideo(video,performance.now(),result=>{const masks=result.confidenceMasks;if(masks?.length){const mask=masks.length>1?masks[1]:masks[0];const player=this.playerLayer(video,mask.getAsFloat32Array(),mask.width,mask.height,canvas.width,canvas.height);this.compose(ctx,player,canvas.width,canvas.height);masks.forEach(item=>item.close());}this.busy=false;});}this.frameId=requestAnimationFrame(()=>this.render());}
 private playerLayer(video:HTMLVideoElement,values:Float32Array,mw:number,mh:number,w:number,h:number){const mask=document.createElement('canvas');mask.width=mw;mask.height=mh;const m=mask.getContext('2d')!,pixels=m.createImageData(mw,mh);for(let i=0;i<values.length;i++){const p=i*4,c=Math.max(0,Math.min(1,values[i])),n=Math.max(0,Math.min(1,(c-.25)/.5)),a=n*n*(3-2*n);pixels.data[p]=pixels.data[p+1]=pixels.data[p+2]=255;pixels.data[p+3]=Math.round(a*255);}m.putImageData(pixels,0,0);const out=document.createElement('canvas');out.width=w;out.height=h;const o=out.getContext('2d')!,x=145,y=145,pw=770,ph=830,mirroredX=w-x-pw;o.save();o.translate(w,0);o.scale(-1,1);o.drawImage(mask,mirroredX,y,pw,ph);o.globalCompositeOperation='source-in';o.drawImage(video,mirroredX,y,pw,ph);o.restore();o.globalCompositeOperation='source-over';return out;}
 private compose(ctx:CanvasRenderingContext2D,player:HTMLCanvasElement,w:number,h:number){ctx.clearRect(0,0,w,h);ctx.drawImage(this.transparentTemplate??this.template,0,0,w,h);ctx.drawImage(player,0,0);this.text(ctx,w);}
 private clip(ctx:CanvasRenderingContext2D,w:number,h:number){ctx.save();ctx.beginPath();ctx.moveTo(w*.16,h*.1);ctx.quadraticCurveTo(w*.5,h*.01,w*.84,h*.1);ctx.lineTo(w*.93,h*.8);ctx.quadraticCurveTo(w*.84,h*.95,w*.5,h*.995);ctx.quadraticCurveTo(w*.16,h*.95,w*.07,h*.8);ctx.closePath();ctx.clip();}
 private text(ctx:CanvasRenderingContext2D,w:number){const gold='#f7d968';const panel=ctx.createLinearGradient(0,940,0,1330);panel.addColorStop(0,'rgba(2,18,88,.18)');panel.addColorStop(.22,'rgba(2,18,88,.82)');panel.addColorStop(1,'rgba(2,10,58,.94)');ctx.fillStyle=panel;ctx.fillRect(128,940,805,385);ctx.strokeStyle='rgba(247,217,104,.6)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(210,1060);ctx.lineTo(850,1060);ctx.stroke();ctx.fillStyle=gold;ctx.textAlign='left';ctx.font='900 84px Chakra Petch';ctx.fillText(String(this.playerNumber).padStart(2,'0'),190,300);ctx.font='700 38px Chakra Petch';ctx.fillText(this.playerPosition,220,348);ctx.textAlign='center';ctx.font='900 62px Chakra Petch';ctx.fillText((this.playerName||'KORA STAR').toUpperCase(),w/2,1035,690);ctx.textAlign='left';ctx.font='800 38px Chakra Petch';[['96 PAC',215,1140],['96 SHO',215,1210],['80 PAS',215,1280],['88 DRI',650,1140],['60 DEF',650,1210],['94 PHY',650,1280]].forEach(([t,x,y])=>ctx.fillText(String(t),Number(x),Number(y)));}
 private fallback(){this.error.set('Background removal could not start. Check your internet connection and reload.');}
 private poster(){const c=this.cardCanvas?.nativeElement;if(!c)return;c.toBlob(b=>{if(!b)return;if(this.posterUrl)URL.revokeObjectURL(this.posterUrl);this.posterUrl=URL.createObjectURL(b)},'image/png');}
 async share(){this.poster();await this.delay(100);if(!this.posterUrl)return;this.isSharing.set(true);try{const b=await fetch(this.posterUrl).then(r=>r.blob()),name=(this.playerName||'star').toLowerCase().replace(/\s+/g,'-'),file=new File([b],`kora-${name}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'My Kora Card',text:'My goal celebration! ⚽'});else this.download();}catch(e){if((e as DOMException).name!=='AbortError')this.download();}finally{this.isSharing.set(false);}}
 download(){this.poster();setTimeout(()=>{if(!this.posterUrl)return;const a=document.createElement('a');a.href=this.posterUrl;a.download=`kora-${this.playerName||'star'}.png`;a.click()},100);}
 async retake(){if(this.frameId)cancelAnimationFrame(this.frameId);if(this.replayUrl)URL.revokeObjectURL(this.replayUrl);this.replayUrl='';this.recordedClip=undefined;await this.openCamera();}
 private delay(ms:number){return new Promise<void>(r=>setTimeout(r,ms));}
 ngOnDestroy(){this.stream?.getTracks().forEach(t=>t.stop());if(this.frameId)cancelAnimationFrame(this.frameId);this.segmenter?.close();if(this.replayUrl)URL.revokeObjectURL(this.replayUrl);if(this.posterUrl)URL.revokeObjectURL(this.posterUrl);}
}
