import {Injectable} from '@angular/core';
import {FaceLandmarker,FilesetResolver,ImageSegmenter,NormalizedLandmark} from '@mediapipe/tasks-vision';

@Injectable({providedIn:'root'})
export class PhotoFilterService {
 private segmenter?:ImageSegmenter;private faceLandmarker?:FaceLandmarker;private products?:HTMLImageElement[];private heroBall?:HTMLImageElement;private brandLogo?:HTMLImageElement;private animationFrame?:number;private runId=0;private capturedBase?:HTMLCanvasElement;private capturedFace?:NormalizedLandmark[];
 private readonly productPaths=['derby','grind','drill','nadi','asphalt','rio','mini','color-01','color-02','color-03','color-04','color-05','color-06','color-07'].map(name=>`./balls/products/${name}.png`);
 private readonly lensAsset='./brand/kora-ball-lens-sprite.png?v=1';

 async render(source:CanvasImageSource,sourceWidth:number,sourceHeight:number,canvas:HTMLCanvasElement){
  const width=1080,height=1350;canvas.width=width;canvas.height=height;const sourceLayer=this.cover(source,sourceWidth,sourceHeight,width,height);
  this.stop();await this.loadModels();const [products,ball,logo]=await Promise.all([this.loadProducts(),this.loadImage(this.lensAsset),this.loadImage('./brand/kora-logo.png')]),base=document.createElement('canvas');base.width=width;base.height=height;const baseCtx=base.getContext('2d')!,timestamp=performance.now(),result=await this.segment(sourceLayer,timestamp);
  this.drawProductWall(baseCtx,products,width,height);this.drawSegmentedPerson(baseCtx,sourceLayer,result,width,height);const face=this.faceLandmarker!.detectForVideo(sourceLayer,timestamp).faceLandmarks[0],ctx=canvas.getContext('2d')!,run=this.runId,draw=(time=performance.now())=>{if(run!==this.runId)return;ctx.clearRect(0,0,width,height);ctx.drawImage(base,0,0);if(face)this.drawBallGlasses(ctx,face,ball,width,height,time);this.frame(ctx,width,height,logo);this.animationFrame=requestAnimationFrame(draw)};draw();
 }

 async startLive(video:HTMLVideoElement,canvas:HTMLCanvasElement,mirror=false){
  this.stop();const width=1080,height=1350,run=this.runId;canvas.width=width;canvas.height=height;await this.loadModels();const [products,ball,logo]=await Promise.all([this.loadProducts(),this.loadImage(this.lensAsset),this.loadImage('./brand/kora-logo.png')]);
  const ctx=canvas.getContext('2d')!,base=document.createElement('canvas');base.width=width;base.height=height;let face:NormalizedLandmark[]|undefined,busy=false,last=0,firstResolved=false;let resolveFirst!:()=>void;const firstFrame=new Promise<void>(resolve=>resolveFirst=resolve);
  const draw=(time:number)=>{if(run!==this.runId)return;if(video.readyState>=2&&!busy&&time-last>75){busy=true;last=time;const source=this.cover(video,video.videoWidth,video.videoHeight,width,height,mirror);this.segmenter!.segmentForVideo(source,time,result=>{if(run!==this.runId){result.confidenceMasks?.forEach(mask=>mask.close());return}const baseCtx=base.getContext('2d')!;baseCtx.clearRect(0,0,width,height);this.drawProductWall(baseCtx,products,width,height);this.drawSegmentedPerson(baseCtx,source,result,width,height);face=this.faceLandmarker!.detectForVideo(source,time).faceLandmarks[0];this.capturedBase=base;this.capturedFace=face;busy=false;if(!firstResolved){firstResolved=true;resolveFirst()}})}ctx.clearRect(0,0,width,height);ctx.drawImage(base,0,0);if(face)this.drawBallGlasses(ctx,face,ball,width,height,time);this.frame(ctx,width,height,logo);this.animationFrame=requestAnimationFrame(draw)};this.animationFrame=requestAnimationFrame(draw);await firstFrame;
 }
 captureBase(){const base=this.capturedBase;if(!base)throw new Error('Live filter is not ready');return new Promise<Blob>((resolve,reject)=>base.toBlob(blob=>blob?resolve(blob):reject(new Error('Photo capture failed')),'image/png'))}
 async renderProcessed(image:HTMLImageElement,canvas:HTMLCanvasElement){this.stop();const width=1080,height=1350,base=this.cover(image,image.naturalWidth,image.naturalHeight,width,height),[ball,logo]=await Promise.all([this.loadImage(this.lensAsset),this.loadImage('./brand/kora-logo.png')]),face=this.capturedFace,ctx=canvas.getContext('2d')!,run=this.runId;canvas.width=width;canvas.height=height;const draw=(time=performance.now())=>{if(run!==this.runId)return;ctx.clearRect(0,0,width,height);ctx.drawImage(base,0,0);if(face)this.drawBallGlasses(ctx,face,ball,width,height,time);this.frame(ctx,width,height,logo);this.animationFrame=requestAnimationFrame(draw)};draw()}
 stop(){this.runId++;if(this.animationFrame)cancelAnimationFrame(this.animationFrame);this.animationFrame=undefined;}
 destroy(){this.stop();this.segmenter?.close();this.faceLandmarker?.close();this.segmenter=undefined;this.faceLandmarker=undefined;}

 private async loadModels(){if(this.segmenter&&this.faceLandmarker)return;const vision=await FilesetResolver.forVisionTasks('./mediapipe/wasm');const [segmenter,faceLandmarker]=await Promise.all([ImageSegmenter.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_segmenter/float16/latest/selfie_segmenter.tflite',delegate:'GPU'},runningMode:'VIDEO',outputCategoryMask:false,outputConfidenceMasks:true}),FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numFaces:1})]);this.segmenter=segmenter;this.faceLandmarker=faceLandmarker;}
 private cover(source:CanvasImageSource,sw:number,sh:number,width:number,height:number,mirror=false){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d')!,scale=Math.max(width/sw,height/sh),dw=sw*scale,dh=sh*scale;if(mirror){ctx.translate(width,0);ctx.scale(-1,1);}ctx.drawImage(source,(width-dw)/2,(height-dh)/2,dw,dh);return canvas;}

 private segment(source:HTMLCanvasElement,timestamp:number){return new Promise<ReturnType<ImageSegmenter['segment']>>(resolve=>this.segmenter!.segmentForVideo(source,timestamp,result=>resolve(result)))}
 private drawSegmentedPerson(ctx:CanvasRenderingContext2D,source:HTMLCanvasElement,result:ReturnType<ImageSegmenter['segment']>,width:number,height:number){const masks=result.confidenceMasks;if(!masks?.length){ctx.drawImage(source,0,0);return}const mask=masks.length>1?masks[1]:masks[0],values=mask.getAsFloat32Array(),mw=mask.width,mh=mask.height,maskCanvas=document.createElement('canvas');maskCanvas.width=mw;maskCanvas.height=mh;const maskCtx=maskCanvas.getContext('2d')!,pixels=maskCtx.createImageData(mw,mh);for(let i=0;i<values.length;i++){const p=i*4,c=Math.max(0,Math.min(1,(values[i]-.18)/.55)),alpha=c*c*(3-2*c);pixels.data[p]=pixels.data[p+1]=pixels.data[p+2]=255;pixels.data[p+3]=Math.round(alpha*255)}maskCtx.putImageData(pixels,0,0);const person=document.createElement('canvas');person.width=width;person.height=height;const personCtx=person.getContext('2d')!;personCtx.drawImage(maskCanvas,0,0,width,height);personCtx.globalCompositeOperation='source-in';personCtx.drawImage(source,0,0);ctx.drawImage(person,0,0);masks.forEach(item=>item.close());}

 private drawProductWall(ctx:CanvasRenderingContext2D,products:HTMLImageElement[],width:number,height:number){ctx.fillStyle='#171717';ctx.fillRect(0,0,width,height);const cols=4,rows=5,cellW=width/cols,cellH=height/rows;for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const image=products[(row*cols+col)%products.length],cx=col*cellW+cellW/2+(row%2?22:-22),cy=row*cellH+cellH/2,size=cellW*.9;ctx.fillStyle=(row+col)%2?'#ededeb':'#d0d2d2';ctx.fillRect(col*cellW+3,row*cellH+3,cellW-6,cellH-6);ctx.drawImage(image,cx-size/2,cy-size/2,size,size)}ctx.fillStyle='rgba(0,0,0,.24)';ctx.fillRect(0,0,width,height);}

 private drawBallGlasses(ctx:CanvasRenderingContext2D,landmarks:NormalizedLandmark[],ball:HTMLImageElement,width:number,height:number,time:number){const average=(a:number,b:number)=>({x:(landmarks[a].x+landmarks[b].x)*width/2,y:(landmarks[a].y+landmarks[b].y)*height/2}),left=average(33,133),right=average(362,263),dx=right.x-left.x,dy=right.y-left.y,distance=Math.hypot(dx,dy),radius=distance*.53,angle=Math.atan2(dy,dx),frame=Math.floor(time/42)%49,sourceSize=360,sourceX=(frame%7)*sourceSize,sourceY=Math.floor(frame/7)*sourceSize;ctx.save();ctx.translate((left.x+right.x)/2,(left.y+right.y)/2);ctx.rotate(angle);for(const x of [-distance/2,distance/2]){ctx.save();ctx.beginPath();ctx.arc(x,0,radius,0,Math.PI*2);ctx.clip();ctx.drawImage(ball,sourceX,sourceY,sourceSize,sourceSize,x-radius,-radius,radius*2,radius*2);ctx.restore()}ctx.restore();}

 private loadProducts(){return this.products?Promise.resolve(this.products):Promise.all(this.productPaths.map(path=>this.loadImage(path))).then(images=>this.products=images)}
 private loadImage(path:string){if(path.endsWith('kora-ball.png')&&this.heroBall)return Promise.resolve(this.heroBall);if(path.endsWith('kora-logo.png')&&this.brandLogo)return Promise.resolve(this.brandLogo);return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>{if(path.endsWith('kora-ball.png'))this.heroBall=image;if(path.endsWith('kora-logo.png'))this.brandLogo=image;resolve(image)};image.onerror=()=>reject(new Error(`Could not load ${path}`));image.src=path})}
 private frame(ctx:CanvasRenderingContext2D,width:number,height:number,logo:HTMLImageElement){const red='#ed1c24',black='#171717';ctx.strokeStyle='#fff';ctx.lineWidth=18;ctx.strokeRect(28,28,width-56,height-56);ctx.strokeStyle=black;ctx.lineWidth=9;ctx.strokeRect(45,45,width-90,height-90);ctx.fillStyle='#fff';ctx.fillRect(45,45,410,94);ctx.drawImage(logo,76,67,270,57);ctx.fillStyle=red;ctx.fillRect(455,45,178,94);ctx.fillStyle=black;ctx.fillRect(633,45,402,94);ctx.fillStyle='#fff';ctx.font='800 21px Chakra Petch';ctx.letterSpacing='4px';ctx.fillText('PRODUCT WALL / FILTER 01',665,101);ctx.fillStyle=black;ctx.beginPath();ctx.moveTo(45,height-190);ctx.lineTo(760,height-190);ctx.lineTo(690,height-45);ctx.lineTo(45,height-45);ctx.closePath();ctx.fill();ctx.fillStyle=red;ctx.beginPath();ctx.moveTo(760,height-190);ctx.lineTo(1035,height-190);ctx.lineTo(1035,height-45);ctx.lineTo(690,height-45);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.font='900 48px Chakra Petch';ctx.fillText('FOOTBALL CULTURE',82,height-111);ctx.drawImage(logo,790,height-138,190,40)}
}
